gmail_username: 'amimecbeepbop@gmail.com'
gmail_password: 'idonthaveapw'

Oauth_client: '136481039092-luqsq4h1dm36t97ojkfu8tpb8qe22qul.apps.googleusercontent.com'
Oauth_secret: 'JW5vTHxYzSQ0KbdNlBm58dcS'
